### ISSUE TITLE
License of the code

### ISSUE THREAD

**Issue by AntonioND** [AntonioND/talesofdagur#1]
Even though the source code is available, it doesn't have a license. I've done the changes needed for the code to build with modern tools, and to convert the graphics at build time, which hasn't required almost any modification to the source code.

@LiraNuna it would be great if you gave permission to license your code under the MIT license (or other license of your choice!). Also, since the MOD player used in this game is also used in WolveSlayer, I could add the license to the source files in that repository too (https://github.com/AntonioND/wolveslayer). I've contacted Payk, who is ok with adding the MIT license to his code, but the MOD player is yours.

**Comment by LiraNuna** [comment]
Most of my public code has been implicitly licensed under the [WTFPL](http://www.wtfpl.net/about/), including ToD.

**Comment by AntonioND** [comment]
Thanks for the confirmation! I've added the license to this repository https://github.com/AntonioND/talesofdagur/commit/de174364a5fec8af8c13e31bde2262182ddc70f8 as well as to the MOD player used in WolveSlayer https://github.com/AntonioND/wolveslayer/commit/3f7744e0ee8390de19464f75c8a8ba979d937e38.
